[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build]
  command = "npm run build"
  publish = "dist"

# Ensure CORS headers are set correctly
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"